[package]
name = "tokio-playground"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tokio-test = "0.4.2"

[dependencies]
rand = "0.8.5"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
